### ISSUE TITLE
运行报错：ImportError: cannot import name 'Undefined' from 'pydantic.fields'

### ISSUE THREAD

**Issue by yinjiaoyuan** [halfzm/faster-propainter#1]
root@xxx:/opt/faster-propainter# python3 start.py 
Traceback (most recent call last):
  File "start.py", line 7, in <module>
    from watermark import pipeline
  File "/opt/faster-propainter/watermark.py", line 13, in <module>
    from model.modules.flow_comp_raft import RAFT_bi
  File "/opt/faster-propainter/model/modules/flow_comp_raft.py", line 3, in <module>
    import ptlflow
  File "/usr/local/lib/python3.8/dist-packages/ptlflow/__init__.py", line 30, in <module>
    from ptlflow.models.base_model.base_model import BaseModel
  File "/usr/local/lib/python3.8/dist-packages/ptlflow/models/base_model/base_model.py", line 31, in <module>
    import lightning.pytorch as pl
  File "/usr/local/lib/python3.8/dist-packages/lightning/__init__.py", line 32, in <module>
    from lightning.app import storage  # noqa: E402
  File "/usr/local/lib/python3.8/dist-packages/lightning/app/__init__.py", line 25, in <module>
    from lightning.app import components  # noqa: E402, F401
  File "/usr/local/lib/python3.8/dist-packages/lightning/app/components/__init__.py", line 1, in <module>
    from lightning.app.components.database.client import DatabaseClient
  File "/usr/local/lib/python3.8/dist-packages/lightning/app/components/database/__init__.py", line 1, in <module>
    from lightning.app.components.database.client import DatabaseClient
  File "/usr/local/lib/python3.8/dist-packages/lightning/app/components/database/client.py", line 22, in <module>
    from lightning.app.components.database.utilities import _GeneralModel
  File "/usr/local/lib/python3.8/dist-packages/lightning/app/components/database/utilities.py", line 20, in <module>
    from fastapi import Response, status
  File "/usr/local/lib/python3.8/dist-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 15, in <module>
    from fastapi import routing
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 22, in <module>
    from fastapi import params
  File "/usr/local/lib/python3.8/dist-packages/fastapi/params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (/usr/local/lib/python3.8/dist-packages/pydantic/fields.py)

**Comment by yinjiaoyuan** [comment]
解决方法：pip install pydantic==1.10.11
