### ISSUE TITLE
propainter与faster-propainter效果对比

### ISSUE THREAD

**Issue by yinjiaoyuan** [halfzm/faster-propainter#2]
首先，faster-propainter确实好快，赞！！！
下图是测试对比，左边的是propainter，右边是faster-propainter的，感觉faster-propainter擦除效果深了点，请问有什么方法可以优化吗？谢谢。

**Comment by yinjiaoyuan** [comment]
<img width="696" alt="faster-propainter测试对比" src="https://github.com/halfzm/faster-propainter/assets/11253528/8b0b9ff2-740c-4848-bab9-5d27929630b5">

**Comment by halfzm** [comment]
裁剪水印那里，裁剪区域改大一点：速度会变慢，效果应该会逼近不裁剪（原版propainter）

**Comment by yinjiaoyuan** [comment]
我把mask图片的矩形区域搞大点显存也是增加不少，容易显存oom。

**Comment by yinjiaoyuan** [comment]
例如原来矩形区域大小是mask_x=0, mask_y=1257, mask_w=1072, mask_h=176，我改大点mask图片的矩形区域为mask_x=0, mask_y=1191, mask_w=1072, mask_h=304，发现显存从10G增加到15G，感觉有点夸张。

**Comment by yinjiaoyuan** [comment]
经过测试对比，感觉裁剪区域变大没什么改善，不知道是不是我测试姿势不对还是怎么样。

**Comment by xsgteamx** [comment]
```python
Processing: myvideo5_seg [335 frames]...
Traceback (most recent call last):
  File "E:\watermark_remover\ProPainter\inference_propainter.py", line 328, in <module>
    flows_f, flows_b = fix_raft(frames[:, f - 1:end_f], iters=args.raft_iter)
  File "E:\watermark_remover\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\watermark_remover\ProPainter\model\modules\flow_comp_raft.py", line 49, in forward
    _, gt_flows_backward = self.fix_raft(gtlf_2, gtlf_1, iters=iters, test_mode=True)
  File "E:\watermark_remover\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\watermark_remover\ProPainter\RAFT\raft.py", line 109, in forward
    corr_fn = CorrBlock(fmap1, fmap2, radius=self.args.corr_radius)
  File "E:\watermark_remover\ProPainter\RAFT\corr.py", line 19, in __init__
    corr = CorrBlock.corr(fmap1, fmap2)
  File "E:\watermark_remover\ProPainter\RAFT\corr.py", line 60, in corr
    return corr  / torch.sqrt(torch.tensor(dim).float())
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.48 GiB (GPU 0; 12.00 GiB total capacity; 8.28 GiB already allocated; 0 bytes free; 12.65 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "E:\watermark_remover\env\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\watermark_remover\env\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\watermark_remover\env\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\watermark_remover\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\watermark_remover\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\watermark_remover\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\watermark_remover\env\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\watermark_remover\app.py", line 203, in remove_watermark
    error_message = result.stderr.decode('utf-8', 'ignore')
AttributeError: 'NoneType' object has no attribute 'decode'
```
RTX 3060 12GB的台式也会OOM 没看到哪里能够调整的.用faster-propainter会好一些吗?

**Comment by yinjiaoyuan** [comment]
> ```python
> Processing: myvideo5_seg [335 frames]...
> Traceback (most recent call last):
>   File "E:\watermark_remover\ProPainter\inference_propainter.py", line 328, in <module>
>     flows_f, flows_b = fix_raft(frames[:, f - 1:end_f], iters=args.raft_iter)
>   File "E:\watermark_remover\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "E:\watermark_remover\ProPainter\model\modules\flow_comp_raft.py", line 49, in forward
>     _, gt_flows_backward = self.fix_raft(gtlf_2, gtlf_1, iters=iters, test_mode=True)
>   File "E:\watermark_remover\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "E:\watermark_remover\ProPainter\RAFT\raft.py", line 109, in forward
>     corr_fn = CorrBlock(fmap1, fmap2, radius=self.args.corr_radius)
>   File "E:\watermark_remover\ProPainter\RAFT\corr.py", line 19, in __init__
>     corr = CorrBlock.corr(fmap1, fmap2)
>   File "E:\watermark_remover\ProPainter\RAFT\corr.py", line 60, in corr
>     return corr  / torch.sqrt(torch.tensor(dim).float())
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.48 GiB (GPU 0; 12.00 GiB total capacity; 8.28 GiB already allocated; 0 bytes free; 12.65 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> Traceback (most recent call last):
>   File "E:\watermark_remover\env\lib\site-packages\gradio\routes.py", line 488, in run_predict
>     output = await app.get_blocks().process_api(
>   File "E:\watermark_remover\env\lib\site-packages\gradio\blocks.py", line 1431, in process_api
>     result = await self.call_function(
>   File "E:\watermark_remover\env\lib\site-packages\gradio\blocks.py", line 1103, in call_function
>     prediction = await anyio.to_thread.run_sync(
>   File "E:\watermark_remover\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "E:\watermark_remover\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
>     return await future
>   File "E:\watermark_remover\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
>     result = context.run(func, *args)
>   File "E:\watermark_remover\env\lib\site-packages\gradio\utils.py", line 707, in wrapper
>     response = f(*args, **kwargs)
>   File "E:\watermark_remover\app.py", line 203, in remove_watermark
>     error_message = result.stderr.decode('utf-8', 'ignore')
> AttributeError: 'NoneType' object has no attribute 'decode'
> ```
> 
> RTX 3060 12GB的台式也会OOM 没看到哪里能够调整的.用faster-propainter会好一些吗?

3060 12G显存也不一定可以的，要看擦除区域的大小和视频帧数。
